# Generated by Django 2.2 on 2020-11-10 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_bookmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookManager',
        ),
    ]
